get:
  summary: Return all CCT Calculations for the authenticated user.
  operationId: getCctCalculations
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/CctCalculationDetail.yml
    "403":
      description: Unknown trainee ID
post:
  summary: Save a new CCT Calculation.
  operationId: createCctCalculation
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CctCalculationDetail.yml
    required: true
  responses:
    "201":
      description: Created
      headers:
        location:
          description: The location of the created calculation
          schema:
            type: string
            format: uri
            example: /api/trainee/cct/calculation/1
      content:
        application/json:
          schema:
            $ref: ../components/schemas/CctCalculationDetail.yml
    "400":
      description: Calculation invalid
      content:
        application/problem+json:
          schema:
            allOf:
              - $ref: ../components/schemas/ValidationError.yml
              - properties:
                  instance:
                    example: /api/trainee/cct/calculator
                  errors:
                    items:
                      properties:
                        pointer:
                          example: "#/id"
                        detail:
                          example: must be null
    "403":
      description: Unknown trainee ID
