openapi: 3.0.3
info:
  title: TIS Self-Service API Endpoints
  license:
    name: MIT
    url: https://opensource.org/license/MIT
  version: 0.0.1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
servers:
  - url: https://trainee.tis.nhs.uk/api
    description: TIS Self-Service
paths:
  /forms/admin/ltft:
    $ref: paths/forms_admin_ltft.yml
  /forms/admin/ltft/count:
    $ref: paths/forms_admin_ltft_count.yml
  /forms/admin/ltft/{formId}:
    $ref: paths/forms_admin_ltft_{formId}.yml
  /forms/admin/ltft/{formId}/approve:
    $ref: paths/forms_admin_ltft_{formId}_approve.yml
  /forms/admin/ltft/{formId}/unsubmit:
    $ref: paths/forms_admin_ltft_{formId}_unsubmit.yml
  /forms/ltft:
    $ref: paths/forms_ltft.yml
  /forms/ltft/{formId}:
    $ref: paths/forms_ltft_{formId}.yml
  /forms/ltft/{formId}/submit:
    $ref: paths/forms_ltft_{formId}_submit.yml
  /forms/ltft/{formId}/unsubmit:
    $ref: paths/forms_ltft_{formId}_unsubmit.yml
  /forms/ltft/{formId}/withdraw:
    $ref: paths/forms_ltft_{formId}_withdraw.yml
  /trainee/cct/calculation:
    $ref: paths/trainee_cct_calculation.yml
  /trainee/cct/calculation/{calculationId}:
    $ref: paths/trainee_cct_calculation_{calculationId}.yml
