type: object
readOnly: true
properties:
  id:
    type: string
    format: uuid
    example: fc13458c-5b0b-442f-8907-6f9af8fc0ffb
  reference:
    description: A custom reference for the LTFT application to aid identification.
    type: string
    example: My Programme - Hours Reduction
  programmeMembershipId:
    type: string
    format: uuid
    example: 2861fb68-6c08-4af5-a3a1-6f561a37b406
  status:
    $ref: ../properties/FormStatus.yml
  created:
    type: string
    format: date
  lastModified:
    type: string
    format: date
