type: object
required:
  - name
  - programmeMembership
properties:
  id:
    type: string
    format: uuid
    example: fc13458c-5b0b-442f-8907-6f9af8fc0ffb
    readOnly: true
  name:
    description: A custom reference for the LTFT application to aid identification.
    type: string
    example: My Programme - Hours Reduction
  programmeMembershipId:
    type: string
    format: uuid
    example: 2861fb68-6c08-4af5-a3a1-6f561a37b406
  status:
    type: object
    readOnly: true
    properties:
      current:
        $ref: ../properties/FormStatus.yml
      history:
        type: array
        items:
          type: object
          properties:
            status:
              $ref: ../properties/FormStatus.yml
            timestamp:
              type: string
              format: date
  created:
    type: string
    format: date
    readOnly: true
  lastModified:
    type: string
    format: date
    readOnly: true
