type: object
readOnly: true
properties:
  id:
    type: string
    format: uuid
    example: fc13458c-5b0b-442f-8907-6f9af8fc0ffb
  formRef:
    description: A human-friendly form reference.
    type: string
    example: ltft_47165_20250101_001
  personalDetails:
    allOf:
      - $ref: ./PersonalDetailsName.yml
      - $ref: ./PersonalDetailsRegistration.yml
  programmeName:
    type: string
    example: General Practice
  proposedStartDate:
    type: string
    format: date
  submissionDate:
    type: string
    format: date
  reason:
    type: string
    example: Caring responsibilities
  daysToStart:
    type: number
  shortNotice:
    type: boolean
  tpd:
    type: object
    required:
      - tpdEmail
      - tpdEmailStatus
    properties:
      email:
        type: string
        format: email
      emailStatus:
        type: string
        enum: [SENT, BOUNCED, REJECTED]
  status:
    $ref: ../properties/FormStatus.yml
  assignedAdmin:
    $ref: ./PersonRole.yml
    example:
        name: Ad Min
        email: ad.min@example.com
        role: ADMIN
