type: object
required:
  - name
  - programmeMembership
properties:
  id:
    type: string
    format: uuid
    example: fc13458c-5b0b-442f-8907-6f9af8fc0ffb
    readOnly: true
  name:
    description: A custom reference for the LTFT application to aid identification.
    type: string
    example: My Programme - Hours Reduction
  change:
    allOf:
      - required:
          - calculationId
          - cctDate
      - properties:
          calculationId:
            type: string
            format: uuid
          cctDate:
            type: string
            format: date
      - $ref: ./CctChange.yml
  declarations:
    required:
      - discussedWithTpd
      - informationIsCorrect
      - notGuaranteed
    properties:
      discussedWithTpd:
        type: boolean
        description: Confirmation that the requested change has been discussed with their TPD.
      informationIsCorrect:
        type: boolean
        description: Confirmation that all information given is correct.
      notGuaranteed:
        type: boolean
        description: Understands that LTFT approval is not guaranteed.
  discussions:
    type: array
    items:
      type: object
      required:
        - name
        - email
        - role
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
    example:
      - name: A. N. Other
        email: a.n.other@example.com
        role: Training Programme Director
      - name: Jo Bloggs
        email: jo.bloggs@example.com
        role: Educational Supervisor
  personalDetails:
    $ref: ./PersonalDetails.yml
  programmeMembership:
    $ref: ./CctProgrammeMembership.yml
  reasons:
    type: array
    items:
      type: string
      example: ["Caring Responsibilities", "Custom Reason"]
  status:
    type: object
    readOnly: true
    properties:
      current:
        $ref: ../properties/FormStatus.yml
      history:
        type: array
        items:
          type: object
          properties:
            status:
              $ref: ../properties/FormStatus.yml
            timestamp:
              type: string
              format: date-time
  created:
    type: string
    format: date-time
    readOnly: true
  lastModified:
    type: string
    format: date-time
    readOnly: true
