type: object
required:
  - name
  - programmeMembership
properties:
  id:
    type: string
    format: uuid
    example: fc13458c-5b0b-442f-8907-6f9af8fc0ffb
    readOnly: true
  name:
    description: A custom reference for the LTFT application to aid identification.
    type: string
    example: My Programme - Hours Reduction
  change:
    allOf:
      - required:
          - calculationId
          - cctDate
      - properties:
          calculationId:
            type: string
            format: uuid
          cctDate:
            type: string
            format: date
      - $ref: ./CctChange.yml
  discussions:
    required:
      - discussedWithTpd
      - tpdName
      - tpdEmail
    properties:
      discussedWithTpd:
        type: boolean
      tpdName:
        type: string
        example: A. N. Other
      tpdEmail:
        type: string
        format: email
        example: a.n.other@example.com
      other:
        type: array
        items:
          type: object
          required:
            - name
            - email
            - role
          properties:
            name:
              type: string
              example: Jo Bloggs
            email:
              type: string
              format: email
              example: jo.bloggs@example.com
            role:
              type: string
              example: Educational Supervisor
  personalDetails:
    $ref: ./PersonalDetails.yml
  programmeMembership:
    $ref: ./CctProgrammeMembership.yml
  reasons:
    type: array
    items:
      type: string
      example: ["Caring Responsibilities", "Custom Reason"]
  status:
    type: object
    readOnly: true
    properties:
      current:
        $ref: ../properties/FormStatus.yml
      history:
        type: array
        items:
          type: object
          properties:
            status:
              $ref: ../properties/FormStatus.yml
            timestamp:
              type: string
              format: date-time
  created:
    type: string
    format: date-time
    readOnly: true
  lastModified:
    type: string
    format: date-time
    readOnly: true
