openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8205/reference
    description: Generated server url
paths:
  /api/programme-membership-type:
    get:
      tags:
        - programme-membership-type-resource
      operationId: getProgrammeMembershipTypes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProgrammeMembershipTypeDto'
  /api/local-office:
    get:
      tags:
        - local-office-resource
      operationId: getLocalOffices
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalOfficeDto'
  /api/local-office-contact:
    get:
      tags:
        - local-office-contact-resource
      operationId: getLocalOfficeContacts
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalOfficeContactDetailsDto'
  /api/local-office-contact-type:
    get:
      tags:
        - local-office-contact-type-resource
      operationId: getLocalOfficeContactTypes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalOfficeContactTypeDto'
  /api/local-office-contact-by-lo-uuid/{localOfficeUuid}:
    get:
      tags:
        - local-office-contact-resource
      operationId: getLocalOfficeContactsByLoUuid
      parameters:
        - name: localOfficeUuid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalOfficeContactDetailsDto'
  /api/local-office-contact-by-lo-name/{localOfficeName}:
    get:
      tags:
        - local-office-contact-resource
      operationId: getLocalOfficeContactsByLoName
      parameters:
        - name: localOfficeName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalOfficeContactDetailsDto'
  /api/immigration-status:
    get:
      tags:
        - immigration-status-resource
      operationId: getImmigrationStatuses
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImmigrationStatusDto'
  /api/grade:
    get:
      tags:
        - grade-resource
      operationId: getGrades
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GradeDto'
  /api/gender:
    get:
      tags:
        - gender-resource
      operationId: getGenders
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenderDto'
  /api/declaration-type:
    get:
      tags:
        - declaration-type-resource
      operationId: getDeclarationTypes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeclarationTypeDto'
  /api/dbc:
    get:
      tags:
        - dbc-resource
      operationId: getDbcs
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DbcDto'
  /api/curriculum:
    get:
      tags:
        - curriculum-resource
      operationId: getCurricula
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurriculumDto'
  /api/covid-change-circs:
    get:
      tags:
        - covid-change-circumstance-resource
      operationId: getCovidChangeCircumstance
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CovidChangeCircumstanceDto'
  /api/college:
    get:
      tags:
        - college-resource
      operationId: getColleges
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CollegeDto'
components:
  schemas:
    ProgrammeMembershipTypeDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
    LocalOfficeDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
        uuid:
          type: string
    LocalOfficeContactDetailsDto:
      type: object
      properties:
        tisId:
          type: string
        localOfficeId:
          type: string
        contactTypeId:
          type: string
        contact:
          type: string
        label:
          type: string
        localOfficeName:
          type: string
        contactTypeName:
          type: string
    LocalOfficeContactTypeDto:
      type: object
      properties:
        tisId:
          type: string
        code:
          type: string
        label:
          type: string
    ImmigrationStatusDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
    GradeDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
        placementGrade:
          type: boolean
        trainingGrade:
          type: boolean
        status:
          type: string
          enum:
            - CURRENT
            - DELETE
            - INACTIVE
    GenderDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
    DeclarationTypeDto:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
    DbcDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
        type:
          type: string
        internal:
          type: boolean
    CurriculumDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
        curriculumSubType:
          type: string
        status:
          type: string
          enum:
            - CURRENT
            - DELETE
            - INACTIVE
    CovidChangeCircumstanceDto:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
    CollegeDto:
      type: object
      properties:
        id:
          type: string
        tisId:
          type: string
        label:
          type: string
